name: $(VersionMajor).$(VersionMinor).$(VersionRevision)

trigger:
  branches:
    include:
    - source
  paths:
    include:
    - src

pool:
#  vmImage: windows-latest
  demands: jdk_8

resources:
  repositories:
  - repository: MasterRepo
    type: GitHub
    endpoint: Bletch1971
    name: Bletch1971/TekTopiaInformation
  - repository: CommonRepo
    type: GitHub
    endpoint: Bletch1971
    name: Bletch1971/TekTopiaCommon
    ref: source

variables:
- name: ApplicationName
  value: 'TekTopiaInformation' #$(Build.DefinitionName)

stages:
- stage: build
  displayName: Build and Publish
  
  jobs:
  - job: build
    displayName: Build and Publish
    workspace:
      clean: all
    
    steps:
    - checkout: self
      persistCredentials: true
      path: 's/${{variables.ApplicationName}}'
    
    - checkout: CommonRepo
      persistCredentials: true
      path: 's/TekTopiaCommon'

