name: $(VersionMajor).$(VersionMinor).$(VersionRevision)

trigger:
  branches:
    include:
    - source
  paths:
    include:
    - src

pool:
#  vmImage: windows-latest
  demands: jdk_8

resources:
  repositories:
  - repository: MasterRepo
    type: GitHub
    endpoint: Bletch1971
    name: Bletch1971/TekTopiaInformation
  - repository: CommonRepo
    type: GitHub
    endpoint: Bletch1971
    name: Bletch1971/TekTopiaCommon
    ref: source

variables:
- name: ApplicationName
  value: 'TekTopiaInformation' #$(Build.DefinitionName)

stages:
- template: azure-pipelines-build.yml@self
  parameters:
    ApplicationName: $(ApplicationName)
    PublishFolder: $(PublishFolder)
    PixelmonVersion: '8.4.0'

- template: azure-pipelines-deploy.yml@self
  parameters:
    DeploymentType: Beta
    DependsOn: build
    ApplicationName: $(ApplicationName)
    PublishFolder: $(PublishFolder)
    RepositoryFolder: $(RepositoryFolderBeta)
    GitEmail: $(GitEmail)
    GitUsername: $(GitUsername)

- template: azure-pipelines-deploy.yml@self
  parameters:
    DeploymentType: Production
    DependsOn: Beta
    ApplicationName: $(ApplicationName)
    PublishFolder: $(PublishFolder)
    RepositoryFolder: $(RepositoryFolderProduction)
    GitEmail: $(GitEmail)
    GitUsername: $(GitUsername)
