name: $(VersionMajor).$(VersionMinor).$(VersionRevision)

trigger:
  branches:
    include:
    - source
  paths:
    include:
    - src
pr: none

pool:
  name: Default
  demands: jdk_8
#  vmImage: windows-latest

resources:
  repositories:
  - repository: MasterRepo
    type: GitHub
    endpoint: Bletch1971
    name: Bletch1971/TektopiaInformation
  - repository: CommonRepo
    type: GitHub
    endpoint: Bletch1971
    name: Bletch1971/TektopiaCommon
    ref: source

variables:
- name: ApplicationName
  value: 'TektopiaInformation'
- name: CommonApplicationName
  value: 'TektopiaCommon'

stages:
- template: azure-pipelines-build.yml
  parameters:
    ApplicationName: $(ApplicationName)
    CommonApplicationName: $(CommonApplicationName)
    PublishFolder: $(PublishFolder)
    TektopiaVersion: '1.1.0'

- template: azure-pipelines-deploy.yml
  parameters:
    DeploymentType: Beta
    DependsOn: build
    ApplicationName: $(ApplicationName)
    PublishFolder: $(PublishFolder)
    RepositoryFolder: $(RepositoryFolderBeta)
    GitEmail: $(GitEmail)
    GitUsername: $(GitUsername)

- template: azure-pipelines-deploy.yml
  parameters:
    DeploymentType: Production
    DependsOn: Beta
    ApplicationName: $(ApplicationName)
    PublishFolder: $(PublishFolder)
    RepositoryFolder: $(RepositoryFolderProduction)
    GitEmail: $(GitEmail)
    GitUsername: $(GitUsername)
